// Generated by CoffeeScript 1.7.1
(function() {
  var updateCart;

  updateCart = function(id, qty, price) {
    return $.post("/Cart/Update", {
      "productId": id,
      "quantity": qty,
      "price": price
    }, function(data) {
      var ref;
      $("#message").addClass("alert alert-success");
      $("#message").html("Order updated");
      if ((ref = $("#product0" + id)) !== null) {
        if (ref.modal !== null) {
          return ref.modal('hide');
        }
      }
    }).fail(function() {
      var ref;
      $("#message").addClass("alert alert-warning");
      $("#message").html("Your order did not update");
      if ((ref = $("#product0" + id)) !== null) {
        if (ref.modal !== null) {
          return ref.modal('hide');
        }
      }
    });
  };

  $(".update-cart").bind('click', function(e) {
    var $select;
    if (e.target.nodeName === 'BUTTON') {
      $select = $(this).find('select');
      return updateCart($select.attr('data-id'), $select.val(), $select.attr('data-price'));
    }
  });

}).call(this);
